### PR TITLE
Adding note about verification of the existance of kube-cache-volume PVC

### PR DESCRIPTION
**Pull request by tovar-rodrigo**

### CODE REVIEW

**Review by iteaguy — CHANGES_REQUESTED** [review]
Let's add the sample manifest here. Just add snippet of what you removed from `go-clouddriver` manifest.

**Comment by iteaguy** [comment]
Valid point @billiford - As background to why we still want to go ahead and do this - We got audited and were told to get rid of some PVs/PVCs from our project since they are not in use. `kube-cache-volume` was one of them. Since we are not using disk with go-cd by default, we are cleaning up what we can. We found references of the one we are deleting in this manifest and would like to remove to avoid confusion. It doesn't hurt to leave it but it doesn't hurt to remove it either. Hence, we are also adding DOCs for what to do if someone does intend to use disk. Hope that clarifies matters.

**Comment by billiford** [comment]
I'm wondering what happened on your end. You shouldn't need to have this documented since your YAMLs aren't referencing a PVC. There shouldn't be any issue starting up Go CD with disk cache in use. Maybe try deploying the YAML with name `spin-go-clouddriver2` and posting the error here and opening an issue if necessary, but this doesn't seem like something that needs to be resolved in this repo, but at the Kubernetes level.

**Comment by iteaguy** [comment]
@billiford - I believe you have a good point. From what I can see now, the names are the same (kube-cache-volume) but the config in `go-clouddriver` is an [emptyDir Volume](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) (not a PV) and the PVC we deleted in [this TFE PR](https://github.com/one-thd/tfe-pr-te-cd-tools/pull/132) has nothing to do with it.

So, for now, we will not take any action on this PR. Once we are done with the PV/PVC cleanup, we will come back here and close this PR.

**Comment by billiford** [comment]
Yeah that sounds correct. Go CD doesn't care if it's some pod-specific disk or PV. We were never able to get the PV working anyway in GKE because GKE didn't allow `ReadWriteMany` for nodes. Deleting those resources from your TF script is definitely the correct approach. If you're able to recreate the error you saw then we should address that, but I didn't want to add a bunch of info if it's unnecessary and would just confuse users.

**Comment by billiford** [comment]
@iteaguy can we close this PR?

**Pull request closed without merging**
